version: "3.7"

services:
  simple-app:
    image: liemly98/simple-app:latest
    restart: always
    build:
      context: .
    ports:
      - 4030:3000
networks:
  default:
    external: true
    name: app-network
