version: "3.7"

services:
  simple-app:
    image: liemly98/simple-app:latest
    build:
      context: .
    ports:
      - 3000:3000
# networks:
#   default:
#     external: true
#     name: app-network
